### ISSUE TITLE
How can I repeat a movement without retyping?

### ISSUE THREAD

**Issue by benlieb** [jeetsukumaran/vim-indentwise#17]
I find the bindings a bit awkward (I know I can change them) but the easiest thing would be to be able to repeat the last movement. Is this possible?

**Comment by jeetsukumaran** [comment]
How do you currently repeat any of your normal mode movements in Vim?

**Comment by benlieb** [comment]
I guess I don't have a way. I know there are plugins. I can repeat searches etc, but don't know how to repeat movements.

**Comment by jeetsukumaran** [comment]
I think the issue is beyond the scope of this plugin? If you find a repeat plugin that works let me know. Or if you can think of a way to do it here, happy to work with a PR.

**Comment by benlieb** [comment]
I don't currently have the time (or vimscript skill) to make a PR, but if I find a plugin that works, I'll let you know. 

Just to clarify, are you saying that you don't actually have a way to repeat the movements yourself?

**Comment by jeetsukumaran** [comment]
Yep.
