### ISSUE TITLE
indent object

### ISSUE THREAD

**Issue by pelodelfuego** [jeetsukumaran/vim-indentwise#7]
Hey !

Once we have motion, How about implementing indent text object ?
It ca be done quite quickly with your plugin but I think this functionality might deserve its own keymap.

Regards.

**Comment by jeetsukumaran** [comment]
Hi! 

This has been discussed [here](https://github.com/jeetsukumaran/vim-indentwise/issues/3).

As noted,  [vim-indent-object](https://github.com/michaeljsmith/vim-indent-object) provides this functionality well enough. I might incorporate it later, but for right now, perhaps installing this plugin side-by-side indentwise might work?
